//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aprendiz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aprendiz()
        {
            this.Asistencia = new HashSet<Asistencia>();
        }
    
        public int Id_aprendiz { get; set; }
        public int Documento_aprendiz { get; set; }
        public string Tipo_Documento_aprendiz { get; set; }
        public string Nombre_aprendiz { get; set; }
        public string Apellido_aprendiz { get; set; }
        public int Telefono_aprendiz { get; set; }
        public string Correo_aprendiz { get; set; }
        public Nullable<int> Numero_ficha { get; set; }
    
        public virtual Ficha Ficha { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asistencia> Asistencia { get; set; }
    }
}
