//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asistencia()
        {
            this.RegistroAsistencia = new HashSet<RegistroAsistencia>();
            this.Soporte = new HashSet<Soporte>();
        }
    
        public int Id_asistencia { get; set; }
        public string Fecha_asistencia { get; set; }
        public string Hora_inicio_asistencia { get; set; }
        public string Hora_fin_asistencia { get; set; }
        public string Detalles_asistencia { get; set; }
        public Nullable<int> Id_Instructor { get; set; }
        public Nullable<int> Id_ficha { get; set; }
        public Nullable<bool> Estado_Asistencia { get; set; }
        public string QrCode { get; set; }
        public Nullable<int> Id_competencia { get; set; }
    
        public virtual Ficha Ficha { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroAsistencia> RegistroAsistencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Soporte> Soporte { get; set; }
        public virtual Competencia Competencia { get; set; }
    }
}
