//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaseDatos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Asistencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asistencia()
        {
            this.Reporte = new HashSet<Reporte>();
            this.Soporte = new HashSet<Soporte>();
            this.RegistroAsistencia = new HashSet<RegistroAsistencia>();
        }
    
        public int Id_asistencia { get; set; }
        [Required(ErrorMessage = "Por favor de colocar la fecha de inicio de la asistencia")]
        public string Fecha_inicio_asistencia { get; set; }
        [Required(ErrorMessage = "Por favor de colocar la fecha de fin de la asistencia")]
        public string Fecha_fin_asistencia { get; set; }
        [Required(ErrorMessage = "Por favor de colocar la hora de inicio de la asistencia")]
        public string Hora_inicio_asistencia { get; set; }
        [Required(ErrorMessage = "Por favor de colocar la hora de fin de la asistencia")]
        public string Hora_fin_asistencia { get; set; }
        [StringLength(500, ErrorMessage = "El nombre no puede exceder los 500 caracteres")]
        public string Detalles_asistencia { get; set; }
        public Nullable<int> Id_usuario { get; set; }
        public Nullable<int> Id_ficha { get; set; }
        public Nullable<int> Id_competencia { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reporte> Reporte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Soporte> Soporte { get; set; }
        public virtual Competencia Competencia { get; set; }
        public virtual Ficha Ficha { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroAsistencia> RegistroAsistencia { get; set; }
    }
}
