//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competencia
    {
        public int Id_competencia { get; set; }
        public string tipo_competencia { get; set; }
        public string Nombre_competencia { get; set; }
        public Nullable<int> Id_ficha { get; set; }
        public Nullable<int> Id_programa { get; set; }
    
        public virtual Programa_formacion Programa_formacion { get; set; }
        public virtual Ficha Ficha { get; set; }
    }
}
