//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Competencia()
        {
            this.Asistencia = new HashSet<Asistencia>();
        }
    
        public int Id_competencia { get; set; }
        public string Nombre_competencia { get; set; }
        public string tipo_competencia { get; set; }
        public Nullable<int> Numero_ficha { get; set; }
        public Nullable<int> Id_programa { get; set; }
        public Nullable<int> Id_Usuario { get; set; }
        public Nullable<bool> Estado_Competencia { get; set; }
    
        public virtual Programa_formacion Programa_formacion { get; set; }
        public virtual Ficha Ficha { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asistencia> Asistencia { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
