//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ficha_has_Usuario
    {
        public int Id_usuario { get; set; }
        public int Id_ficha { get; set; }
        public string TipoUsuario { get; set; }
    
        public virtual Ficha Ficha { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
