//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor
    {
        public int Id_instructor { get; set; }
        public int Documento_instructor { get; set; }
        public string Tipo_Documento_instructor { get; set; }
        public string Nombre_instructor { get; set; }
        public string Apellido_instructor { get; set; }
        public int Telefono_instructor { get; set; }
        public string Correo_instructor { get; set; }
        public string Tipo_instructor { get; set; }
        public Nullable<int> Id_ficha { get; set; }
    
        public virtual Ficha Ficha { get; set; }
    }
}
