//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaseDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDAssistsADSOEntities : DbContext
    {
        public BDAssistsADSOEntities()
            : base("name=BDAssistsADSOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asistencia> Asistencia { get; set; }
        public virtual DbSet<Competencia> Competencia { get; set; }
        public virtual DbSet<Ficha> Ficha { get; set; }
        public virtual DbSet<Programa_formacion> Programa_formacion { get; set; }
        public virtual DbSet<Reporte> Reporte { get; set; }
        public virtual DbSet<Soporte> Soporte { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual ObjectResult<string> ValidarUsuarios(string correo, string contraseña)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var contraseñaParameter = contraseña != null ?
                new ObjectParameter("Contraseña", contraseña) :
                new ObjectParameter("Contraseña", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ValidarUsuarios", correoParameter, contraseñaParameter);
        }
    
        public virtual ObjectResult<string> ValidarUsuarios1(string correo, string contraseña)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var contraseñaParameter = contraseña != null ?
                new ObjectParameter("Contraseña", contraseña) :
                new ObjectParameter("Contraseña", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ValidarUsuarios1", correoParameter, contraseñaParameter);
        }
    
        public virtual int RegistrarUsuario(string tipo_Documento_usuario, Nullable<int> documento_usuario, string nombre_usuario, string apellido_usuario, Nullable<int> telefono_usuario, string correo_usuario, string contrasena_usuario, string tipo_usuario, string tipo_instructor, ObjectParameter registrado, ObjectParameter mensaje)
        {
            var tipo_Documento_usuarioParameter = tipo_Documento_usuario != null ?
                new ObjectParameter("Tipo_Documento_usuario", tipo_Documento_usuario) :
                new ObjectParameter("Tipo_Documento_usuario", typeof(string));
    
            var documento_usuarioParameter = documento_usuario.HasValue ?
                new ObjectParameter("Documento_usuario", documento_usuario) :
                new ObjectParameter("Documento_usuario", typeof(int));
    
            var nombre_usuarioParameter = nombre_usuario != null ?
                new ObjectParameter("Nombre_usuario", nombre_usuario) :
                new ObjectParameter("Nombre_usuario", typeof(string));
    
            var apellido_usuarioParameter = apellido_usuario != null ?
                new ObjectParameter("Apellido_usuario", apellido_usuario) :
                new ObjectParameter("Apellido_usuario", typeof(string));
    
            var telefono_usuarioParameter = telefono_usuario.HasValue ?
                new ObjectParameter("Telefono_usuario", telefono_usuario) :
                new ObjectParameter("Telefono_usuario", typeof(int));
    
            var correo_usuarioParameter = correo_usuario != null ?
                new ObjectParameter("Correo_usuario", correo_usuario) :
                new ObjectParameter("Correo_usuario", typeof(string));
    
            var contrasena_usuarioParameter = contrasena_usuario != null ?
                new ObjectParameter("Contrasena_usuario", contrasena_usuario) :
                new ObjectParameter("Contrasena_usuario", typeof(string));
    
            var tipo_usuarioParameter = tipo_usuario != null ?
                new ObjectParameter("Tipo_usuario", tipo_usuario) :
                new ObjectParameter("Tipo_usuario", typeof(string));
    
            var tipo_instructorParameter = tipo_instructor != null ?
                new ObjectParameter("Tipo_instructor", tipo_instructor) :
                new ObjectParameter("Tipo_instructor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegistrarUsuario", tipo_Documento_usuarioParameter, documento_usuarioParameter, nombre_usuarioParameter, apellido_usuarioParameter, telefono_usuarioParameter, correo_usuarioParameter, contrasena_usuarioParameter, tipo_usuarioParameter, tipo_instructorParameter, registrado, mensaje);
        }
    }
}
