//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte
    {
        public int Id_reporte { get; set; }
        public string Nombre_reporte { get; set; }
        public string Descripcion_reporte { get; set; }
        public string Tipo_reporte { get; set; }
        public Nullable<int> Id_asistencia { get; set; }
    
        public virtual Asistencia Asistencia { get; set; }
    }
}
