//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaseDatos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Asistencia = new HashSet<Asistencia>();
            this.Ficha_has_Usuario = new HashSet<Ficha_has_Usuario>();
            this.RegistroAsistencia = new HashSet<RegistroAsistencia>();
            this.Soporte = new HashSet<Soporte>();
            this.Soporte1 = new HashSet<Soporte>();
        }
    
        public int Id_usuario { get; set; }
        public string Tipo_Documento_usuario { get; set; }
        public Nullable<int> Documento_usuario { get; set; }
        [Required(ErrorMessage = "Por favor de ingresar el nombre del usuario")]
        public string Nombre_usuario { get; set; }
        public string Apellido_usuario { get; set; }
        public Nullable<decimal> Telefono_usuario { get; set; }
        [Required(ErrorMessage = "Por favor de ingresar el correo del usuario")]
        public string Correo_usuario { get; set; }
        [Required(ErrorMessage = "Por favor de ingresar la contraseña del usuario")]
        public string Contrasena_usuario { get; set; }
        public string Tipo_usuario { get; set; }
        public Nullable<bool> Estado_Usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asistencia> Asistencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ficha_has_Usuario> Ficha_has_Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroAsistencia> RegistroAsistencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Soporte> Soporte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Soporte> Soporte1 { get; set; }
    }
}
